### ISSUE TITLE
Cyrillic and search on some sites

### ISSUE THREAD

**Issue by e2li1386** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#1]
Good afternoon. There are resources that use their own encoder to search. For example, there is a site nnmclub.to and if you implement its search engine and search for Cyrillic alphabet or in general, starting with the version of Firefox 75 browser, then the search either does not return anything with any encoder that is in the add-on, or it displays, but hieroglyphs. I gave 2 screenshots with the search for the Cyrillic alphabet as an example.
![1](https://user-images.githubusercontent.com/63337524/78754769-be145600-7980-11ea-981d-f2d4693508bc.png)
![2](https://user-images.githubusercontent.com/63337524/78754779-c10f4680-7980-11ea-8948-1c940169ab32.png)

**Comment by YoshifumiFuyuno** [comment]
Hi. Thank you for the information.
It appears that changes have been made in Firefox 75 that are not mentioned in the release notes.
I dealt with it. Please wait until it is updated in AMO(addons.mozilla.org).

**Comment by YoshifumiFuyuno** [comment]
It seems that it was released in AMO.
I will close this, but please let me know if you have any problems.
Thank you.

**Comment by e2li1386** [comment]
Work. Thx :D
