### ISSUE TITLE
Multiple Search: Search windows open in reversed order

### ISSUE THREAD

**Issue by gthbububba** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#15]
If you set up a Multiple Search and add your engides between
Multiple Search Start
engine1
engine2
engine3
Multiple Search Stop

the results are opend in new windows
engine3
engine2
engine1

while expected behavior is

engine1
engine2
engine3

This is confusing.

Firefox 88.0
SPC 6.0.1

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thank you for reporting.

This add-on opens URLs in order from 1.
Unless set to open in the next current tab, it is the browser settings or other add-ons that control the tab position.

In any case, I don't think the order of the tabs is important for multiple searches, what do you think?

Best regards

**Comment by gthbububba** [comment]
I have to apologize. Everything works perfectly. I was getting confused as the newest search result (engine3) was focused while was expecting engine1 to be focussed.
Sorry about that.
