### ISSUE TITLE
"translat" is blocked

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#16]
Hi! I just started using your add-on after you so kindly pointed to it in the SSS bug report. I will be posting several bug or feature requests.

In the options: Under highlight - blocklist, the value "translat" is added. It seems like you'd like this to block https://translate.google.com, but it seems to be too general and it looks like it'll also catch a bunch of other websites and webpages. For example, what if someone writes a blog post about translating ancient texts, and the string "translat" is in the blog post's URL.

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thank you for reporting.

I haven't been active on GitHub lately, so I'm mistaken for someone.

And first of all, this is a project that is being created in my spare time, so I can't devote much time to it.
Suggestions and the like are greatly appreciated, but please understand that I can't respond to all of them.
***
It was intended to block multiple translation sites, not just Google Translate.
If you're concerned about false positives, please remove the "translat" and specify the exact URL.
e.g. https://translate.google.com/

Best regards

**Comment by cheater** [comment]
Thanks, yeah, I mistook the person who pointed me to this addon for the author.

I had to put those requests somewhere so they don't get lost. I hope you don't mind :-) A bunch of them should be easy to implement... If you can help me figure out how to build this addon for Windows, I will try implementing those myself.

**Comment by cheater** [comment]
Could I suggest that you block the problematic sites one by one rather than blocking a fairly generic string like "translat"? It could lead to users being surprised that the plugin doesn't work on a specific site.

Why is it blocked on translate.google.com? Performance issue? Thanks
