### ISSUE TITLE
UI Freezes when editing Options

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#18]
This is a very annoying issue. :(

When interacting with the options, I get freezes that take several seconds (even when doing something simple, like eg collapsing a menu). It's only my guess, but maybe SPC has a piece of javascript running on every open tab, and maybe when you interact with the UI, the options page tries to communicate with every such piece of javascript. I have very, very many tabs open (hundreds of windows, with hundreds of tabs), so if you run javascript in every tab, this would cause that. The freezes happen every time I interact with the UI, so adding a new search engine is very painful.

I hope you can improve this, please!

**Comment by YoshifumiFuyuno** [comment]
Can this be reproduced with SSS?

**Comment by YoshifumiFuyuno** [comment]
I have released a new version.
Please let me know if this issue has been improved or not.

**Comment by cheater** [comment]
There's still a bit of an issue. When dragging the items, the update rate is pretty slow. Maybe one frame per second or two seconds.

**Comment by YoshifumiFuyuno** [comment]
Could not reproduce.
Is it slow during the drag? Or is it slow to drop?
If you are dragging, the library(sortablejs) controls it, so I can't do anything.

If possible, can you take a video?
You can use Windows built-in screen recorder or ScreenToGif for shooting.

**Comment by cheater** [comment]
Yeah, I'll take a video. In fact I'll use my mobile phone, so I know
framerate is not affected by what's going on on the computer. I'll put it
on youtube. Thanks for still looking into this.

**Comment by cheater** [comment]
While taking the video, I figured out what happens when the list stops
responding. When I'm dragging the menu item, sometimes my mouse cursor will
go to the left of the list. During that time, it looks like the list is
unresponsive. The cursor changes to a "crossed out" road sign. I think it
would be better if the list kept on moving even if the cursor is left of
it. I understand that's behavior from sortablejs, so it might either be
something they already do, or you might have to request the feature from
them.

**Comment by YoshifumiFuyuno** [comment]
Oh, the left side doesn't respond because it's out of element range.
Change the DOM to handle it.
Done. Version 6.2.1
