### ISSUE TITLE
Import search engines only

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#21]
When restoring from backup, allow importing search engines only (eg from SSS)

**Comment by YoshifumiFuyuno** [comment]
You can do this by editing the JSON to make it engine only.

**Comment by cheater** [comment]
Thanks. Good to know. That doesn't seem to be stated anywhere. This feature request can serve as some sort of "documentation" at least :-)

**Comment by cheater** [comment]
I would like to mention that this is not a full solution - if the JSON only contains search engines, other settings will be reset to default. (see #47)
