### ISSUE TITLE
Import from backup - add search engines instead of overwriting them

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#22]
When importing from backup, have an option to add search engines to the ones that already exist, instead of getting rid of the existing ones.

Have checkboxes for every search engine that is going to be added. Checked = this search engine gets added; Unchecked = this search engine does not get added.

**Comment by YoshifumiFuyuno** [comment]
Please merge the JSON.

**Comment by cheater** [comment]
This is a difficult extra step for some users. I would like to share these settings with users who are not programmers. Could you reconsider adding this feature please?
