### ISSUE TITLE
Support importing from SSS last version

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#23]
Support importing from SSS last version, 3.47.4. The documentation indicates you only allow importing up to version 3.33.0.

**Comment by YoshifumiFuyuno** [comment]
Can't you import?
What specific problems are you encountering?

**Comment by cheater** [comment]
I haven't tried. The docs mention version 3.33.0, so I assumed that there was a reason for that. I'll try and see if there are any issues.

**Comment by YoshifumiFuyuno** [comment]
This add-on is based on SSS Version 3.33.0, it is that version that I can guarantee.
It's too much of a burden for me to check every time the SSS version goes up.
If there is a problem, someone should report it.

**Comment by cheater** [comment]
Thank you for clarifying.

**Comment by YoshifumiFuyuno** [comment]
I confirmed that the latest version of SSS configuration file can also be converted and imported correctly. (All default settings)
