### ISSUE TITLE
Change context menu accelerator key

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#24]
Let me change context menu accelerator key. It is currently set to "m" and it is hard to find that key with the left hand. I have to move my right hand from the mouse to the M key and that takes a long time. It does not accelerate my work :-)

I would like to use "d", so that I can press it without getting my right hand off the mouse, but others might want to use another key. Please set an option where you can set the key. If possible, please make sure you support F keys (F1-F24), as well as ` (backtick), and 1234567890.

**Comment by YoshifumiFuyuno** [comment]
Done. Version 6.2
Related #28
