### ISSUE TITLE
Cosmetic - SPC context menu text

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#28]
Please could you improve the context menu text a little bit? Currently it is `search: "searchtext"(M)`. Please change it to `Search for “searchtext” (M)`.

Changes:
- first letter capitalized like all other menu items
- space before accelerator key
- no `:`, use "for" instead, like other search addons (not just SSS, but others as well) as well as the default functionality in Firefox. Less visual clutter.
- use unicode quotation marks like Firefox does. Left one is `  “  ` (Unicode `201C`, UTF-8 `E2809C`), right one is `  ”  ` (Unicode `201D`, UTF-8 `E2809D`)

Thank you!

**Comment by YoshifumiFuyuno** [comment]
I might do it, but it's a low priority.

**Comment by cheater** [comment]
Thank you, I would appreciate it.

**Comment by YoshifumiFuyuno** [comment]
Done. Version 6.2
Added the ability for users to make changes freely.

**Comment by cheater** [comment]
Would you like to change the default to `Search for “%s” (&F)` so it is in line with other search add-ons and Firefox built in functionality? F is also unused in the context menu and it's easily accessible by the left hand when it's in the home position. Chrome's right click menu has a "Refresh" menu item with two accelerators: R and F, so you can override F.
