### ISSUE TITLE
Open in link and Copy to clipboard

### ISSUE THREAD

**Issue by dishanrajapaksha** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#3]
**Is your feature request related to a problem? Please describe.**

_First of all, thank you for porting Swift Selection Search to Chromium browsers._

Swift Selection Search has a pop up buttons to open the selection as a link and to copy the selection to clipboard.
Since this is a fork, I was expecting those features to be available but could not find them in the extension settings.

**Describe the solution you'd like**

- A popup button with the ability to open the selection as a link.
- A popup button with the ability to copy the selection to clipboard.

**Additional context**

Please refer to these screenshots from Swift Selection Search.

![image](https://user-images.githubusercontent.com/9119289/108623476-50bcc700-7465-11eb-8b04-bf0c80fab196.png)
![image](https://user-images.githubusercontent.com/9119289/108623510-6cc06880-7465-11eb-8d55-ae9b84acfe51.png)

Thank you again.

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thank you for reporting.

Both functions are available.
It was explained on the Wiki, which anyone can freely edit, but
it seems that @KHALEEJCHAT has deleted the page. (Why?

![log](https://user-images.githubusercontent.com/9511854/108697468-3eff2080-7546-11eb-9fce-6d4d8842d5a8.png)


I reverted to the Wiki before it was deleted.
[Example engines](https://github.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/wiki/Example-engines)
- Open as link
- copyToClipboardAsText
- copyToClipboardAsHtml
- copy in Markdown

If you have any questions, please ask.

Best regards

**Comment by dishanrajapaksha** [comment]
**Thank you!** Worked perfectly!
