### ISSUE TITLE
Inline documentation help

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#30]
First of all, I really appreciate you taking up the mantle from SSS and all the work you did. The new features are great, especially POST support and "Multiple Search". This is a very complex plugin. Your work on it is very appreciated. However, a big portion of the text in the plugin is somewhere between "somewhat obscure" to "I have to guess what this does". This is especially important in the Options page, but also in the Wiki. For a better user experience, a lot of the texts should be rewritten by a native English speaker who will talk to you about what specific features mean, and explain them using improved text, that you can then display in the options page.

I hope this improvement will help a lot of other users find SPC to be very useful! Thank you!

**Comment by YoshifumiFuyuno** [comment]
I agree.
I am not good at English, so I think the text is very difficult to understand.
To be honest, writing English text takes many times longer than programming time.

**Comment by cheater** [comment]
Not necessarily "very" difficult but docs can always be improved in any project. It serves its purpose in a rudimentary way for now.
