### ISSUE TITLE
Allow turning off "Options" in the context menu

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#31]
Allow turning off the "Options" menu item in the context menu. I can already access it elsewhere. It's good to have it on by default, especially for new users, but not necessary in the long run, and takes up space.

**Comment by YoshifumiFuyuno** [comment]
It is possible from the setting.
Please remove the check mark.

**Comment by cheater** [comment]
Ahhh, thank you, I should have looked more closely. The screen is a bit busy so I just didn't see it...

I performed a full-text search for "options" but the "search engines" section was shut. So I didn't find it. I didn't think to search under "search engines" because the "options" menu isn't a search engine...
