### ISSUE TITLE
Do not open new tabs on installation

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#32]
When the extension is installed, new tabs are opened with the readme and the instructions. This is a good idea, but it has some issues. My request is: Please do not open pop ups and instead create other abilities for users to find the documentation.

This is an issue because every time the extension is updated, the tabs will be opened again. This is a problem for the following reason: Let's say I have a window open with 100 tabs. The currently active tab us tab number 57. The new tabs will go on the end of the window and take me away from the tab that I had open. Now I won't be able to find the tab again. It's very aggravating when this happens.

There is also another issue. When the new tabs are opened, the user might just habitually close them and not even know about them. Or they might not even see that the tabs have been opened.

Instead, please add a menu item in the context menu and the popup that will open a new tab on the documentation. This will be easily discoverable by the user. The user will see it every time they open the context menu. Please also make it possible to delete this option.

**Comment by YoshifumiFuyuno** [comment]
Tabs are opened only during the initial installation.
It doesn't do anything when the extension is updated.

There is also a link to the Wiki in Instructions on the options page.
