### ISSUE TITLE
JavaScript based search engine

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#36]
Please add a type of menu entry that just runs a piece of JavaScript. It should be a function that takes the following parameters:

- `selectionText`: the currently selected text, or null
- `pageURL`: the address of the current page
- `imageUri`: the address of the image that was right clicked (if at all), or null
- `domElement`: the dom element that was right clicked, or null
- `linkHref`: the address the link that was right clicked, or null
- `clipboard`: the contents of the clipboard, or null
- `searchMenuName`: the name that this menu item has in SPC (without accelerator key added)
- `searchMenuUID`: the UID of the search menu item

The user is presented with an expandable text area to paste in or edit their code. The function returns a list of URLs to open in new tabs/windows/etc (whatever the current setting is). If the function returns null, nothing is done (but the function is also free to call `window.open()` and do other stuff).

This code could look like this:

```
function search(searchText) {
   return ["https://www.google.com/search?client=firefox-b-d&q=" + searchText]
}
```

or it could also look like this (anonymous function):

```
function search(searchText) {
   return ["https://www.google.com/search?client=firefox-b-d&q=" + searchText]
}
```

or it could be a lambda function:
```
searchText => ["https://www.google.com/search?client=firefox-b-d&q=" + searchText]
```

It could also be very complicated code. For some situations you need to process the search query. For example: remove punctuation and brackets, add quotation marks around every word, remove common words. This is all stuff that needs to be done before the search query becomes useful. I've spent several hours doing that repeatedly yesterday, and it's something I can see myself using very often. Another situation is if you want to communicate with an external search program that's running on your desktop. You might want to communicate with it by doing a http POST or GET request, but you don't need to open a search results tab, because the search results show up in the program's window.

**Comment by YoshifumiFuyuno** [comment]
You can use Bookmarklet.
cf. [Bookmarklet APIs](https://github.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/wiki/Bookmarklet-APIs)

**Comment by cheater** [comment]
Would this work for enabling and disabling elements of the context menu, as well?

**Comment by YoshifumiFuyuno** [comment]
Yes if the context menu was not created by the SPC but you created with a script.

**Comment by cheater** [comment]
I'm not sure what that means. Context menu created with a script?
