### ISSUE TITLE
Page-specific search engines

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#37]
Please allow page-specific search engines. This means that for every search engine, there should be both a whitelist and a blacklist. It works like this:

1. If whitelist is empty go on to processing blacklist.
2. If whitelist is not empty, check every line of whitelist. If there is an exact match, continue to blacklist. If the entry ends or starts with `*`, then match using wildcards. For example, `*://www.google.com` will match if we are currently on `https://www.google.com`, but not if we are currently on `https://www.google.com/search`. If there is a wildcard match, continue to blacklist.
3. If the whitelist is not empty, and there have been no matches, do not show this search engine in the context menu.
4. Process blacklist.
5. If the whitelist is empty, and the blacklist is empty, show the search engine in the context menu.
6. If the whitelist is not empty and the blacklist is not empty, process blacklist like the whitelist in 2. A match means the search engine will not be shown in the context menu.
7. If the whitelist is empty and the blacklist is not empty, do the same thing as in 6.

This would be very useful because often when I'm on a specific page I want to search for a very specific query. For example, if I'm on IMDB, I might want to have Netflix at the very top of the search engine list, and bound to the A accelerator key (using feature request #27). But for normal usage, when I'm not on IMDB, I don't want that. Or similarly if I'm visiting a Steam game page, I want to search a game price comparison site, but only when I'm on Steam.

**Comment by YoshifumiFuyuno** [comment]
For popup, you can use Engine filter and Auto-execute Bookmarklet to do something similar.
