### ISSUE TITLE
Unable to import Firefox search engines

### ISSUE THREAD

**Issue by jdt1** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#4]
**Description:**
I cannot import my Firefox search engines. I have located the "search.json.mozlz4" file, but after opening it via the file dialog, nothing happens. I have also tried to export the search engines from the Firefox plug-in, but I am unable to import them in the Edge plug-in. The first time I tried to import the file, I got a message similar to "error opening file". The next times that I tried I got no message anymore. The search engines are not imported though.

**To Reproduce**
- Locate and open the "search.json.mozlz4" file under "Load Firefox search engines"
or:
- Export the search engines json file from the Firefox plug-in, and import it into the Edge plug-in

**Expected behavior**
The search engines from the Firefox plug-in are imported.

**Actual behavior**
Nothing seems to happen.

**OS/versions:** 
 - OS: Windows 10 1909 10.0.18363.1379
 - Browser Firefox 86, Edge 88.0.705.81 
 - Firefox plug-in: Swift Selection Search 3.47.3
 - Edge plug-in: Search from Popup or ContextMenu 4.7

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thank you for reporting.

Firefox 85 "search.json.mozlz4" was successfully imported.
Firefox 86 "search.json.mozlz4" could not be imported.

Mozilla seems to have changed the format in Firefox 86.

Fix in the next version.

I've created a script for when you're in a hurry.
https://drive.google.com/file/d/1MhXgF_bjfHcmZXLhFmW6qoUQT4yg93ew/view?usp=sharing

VirusTotal result: https://www.virustotal.com/gui/file/9c42cc39e9f46441c88254b440e59136ad3fa6cdba1083b19b3c9ace3642038c/summary

Drag and drop "search.json.mozlz4" to "FixSearchEngine.bat" creates a modified "search.json.mozlz4" on the desktop.
Please import.

Best regards

**Comment by jdt1** [comment]
Many thanks for replying so quickly! Unfortunately, the script does not seem to work for me. I dragged the search.json.mozlz4 file to the script and it ran. I can also see the file is modified. However, I am still unable to import the file. I tried with and without ticking the "Add to folder" box.

Kind regards

**Comment by jdt1** [comment]
Because I was trying to import my search engines from Firefox, I didn't notice that the search engine selection box actually does not come up when I select some text. So maybe there's a bigger underlying problem. Is there anything I can do/check to help resolve the problem?

**Comment by YoshifumiFuyuno** [comment]
Hi.

- Popup
  By default, popup appears when you **drag** an image, selected text, or link, but you can choose from the following behaviors.
  add-on options -> "Popup/icons behaviour" -> "Opening behaviour":
  (Off / Auto / Hold Alt / Keyboard-only / Middle mouse button / Click / Drag)
  https://github.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/wiki/Instructions#about

- Import
  You can only import search engines that you added yourself, is that okay?
  Engines built into Firefox (e.g. Google, Bing and DuckDuckGo) don't have a URL in "search.json.mozlz4".
  https://github.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/wiki/Instructions#add-search-engine

  If it's not a built-in engine, can you upload "search.json.mozlz4"?

**Comment by jdt1** [comment]
Hi,

I see, the dragging does work.

I assumed importing the _search.json.mozlz4_ would import the search engines from the _SSS plug-in in Firefox_. However I'm now thinking this file only contains the Firefox browser search engines. Is this correct? 

Still, nothing seems to be getting imported. I've attached my _search.json.mozlz4_ file to this message.

**Steps to reproduce _search.json.mozlz4_ not getting imported:**
1. Remove all search engines from SPC
2. Open _search.json.mozlz4_ file through "Select _search.json.mozlz4_" button in SPC options

It this moment, it is more interesting for me to import the exported search engines from the Firefox SSS plug-in. However, when I try to import the file, I get this error.
![image](https://user-images.githubusercontent.com/8831830/109855608-c9d3cf80-7c58-11eb-8b0f-020e031ba5a7.png)


Kind regards

**Comment by jdt1** [comment]
After some looking around in the source code (which I cannot find in this repository btw), it seems the error comes from here. The extension expects data of the type "application/json", however it gets data in the type "text/plain". I'm not sure why this is happening as it is a bit hard to read the minified js, even after pretty printing it. 

![wrong data type](https://user-images.githubusercontent.com/8831830/109858859-a3179800-7c5c-11eb-9d6f-1e0eb0f94dfb.png)

**Comment by YoshifumiFuyuno** [comment]
Thank you for uploading.

> Is this correct?

That's right.

dejsonlz4 Your search.json.mozlz4
`{"version":6,"engines":[{"_name":"Google","_isAppProvided":true,"_metaData":{}},{"_name":"Amazon.com","_isAppProvided":true,"_metaData":{}},{"_name":"Wikipedia (en)","_isAppProvided":true,"_metaData":{}},{"_name":"Bing","_isAppProvided":true,"_metaData":{}},{"_name":"DuckDuckGo","_isAppProvided":true,"_metaData":{}},{"_name":"eBay","_isAppProvided":true,"_metaData":{}}],"metaData":{"useSavedOrder":false}}`
You will notice that the "search.json.mozlz4" you uploaded does not contain a URL that you can import.

I'll say it again.
"Load Firefox search engines (search.json.mozlz4)" can only import search engines that you added yourself.
For reference: How to add
https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox#w_add-search-engines
***
If you want to import settings from SSS
1. on SSS, "Storage & backup" -> "Export to file"
2. on SPC, "Storage & backup" -> "Import from file"

I tested it here and was able to import it without any problems.
settings file used for test: [SSSv3.47.3-Export-All_default_settings.zip](https://github.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/files/6082666/SSSv3.47.3-Export-All_default_settings.zip)
However, compatibility with the latest SSS is not guaranteed and is not recommended.

**Comment by jdt1** [comment]
Thanks for your reply. It seems there's multiple ways to add search engines to Firefox and I used a different one ("add keyword for search").

I have tried to import the settings just like you describe, however it does not work unfortunately. If you would upload the code to this repository I could have a look and possibly help add this functionality. :)

**Comment by YoshifumiFuyuno** [comment]
I understand.
It's called Smart keywords, not One-Click Search Engines, but actually bookmarks.
There is no encoding setting for this, and it is currently not supported as some sites have garbled characters.
If there are many requests, we will make it possible to import it.

`application/json` is set by the browser and nothing is done on the add-on side.
Perhaps the json MIME type is incorrectly registered on your Windows.
In Windows 10 20H2 with a clean installation, it is registered as follows.
![Win10-20H2](https://user-images.githubusercontent.com/9511854/110100816-2f08fb80-7de6-11eb-98b7-c573992d9053.png)
I have attached the reg file for fix.
[json.zip](https://github.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/files/6089722/json.zip)

The next version will remove the MIME type check.

**Comment by jdt1** [comment]
Interesting. The registry key is correctly set on my machine (same as your
.reg file). It seems that Edge is sending the wrong MIME type. I'll have a
look later.

Op vr 5 mrt. 2021 om 11:19 schreef Yoshifumi Fuyuno <
notifications@github.com>:

**Comment by YoshifumiFuyuno** [comment]
Hi.

It's strange.
After all, what the add-on is doing is the following behavior
https://gistpreview.github.io/?c5dddfbb156880763033c7a3e31e473c
source code: https://gist.github.com/c5dddfbb156880763033c7a3e31e473c

Just in case, the file extension is still json, right?

In any case, I submitted the version without MIME type check to the examination.
Mozilla seems to have passed the review.
Experience has shown that Microsoft is slow at  review. Please wait for a while.

Best regards

**Comment by jdt1** [comment]
Hi,

Something strange seems to be going on:

![image](https://user-images.githubusercontent.com/8831830/110371129-d71ffe00-804c-11eb-8cff-4ce1102e84e1.png)

As you can see, the browser reports the file as "text/plain" even though the extension is .json. 

As suggested by [this ](https://textslashplain.com/2018/07/26/be-skeptical-of-client-reported-mime-content-types/) website I have also checked Content Type key in the registry. Thanks for removing the MIME type check, I hope Microsoft will approve the change soon.

Kind regards

**Comment by YoshifumiFuyuno** [comment]
Hi.

Close this issue.
If you have a problem, you can always reopen it.

Best regards
