### ISSUE TITLE
Importing settings that don't include an option sets that option to default value

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#47]
### Describe the bug

I wanted to import only the search engines from SSS, so I created a json file that only contained the search engines. Some of the settings got reset to the default value.

### To Reproduce

Create json backup file and remove some options

### Expected behavior

Options remain as they are before import

### Actual behavior

Options get reset to default

### Your Environment

```markdown
- OS: Windows 10
- Browser Firefox 97
- Extension Version 6.2
```

### Additional context

Not resetting options would be good if you want to do a partial import just to get your search engines, or if you want just all your settings but not search engines.

**Comment by YoshifumiFuyuno** [comment]
Could not reproduce.
What exactly are the options that are reset to default?

**Comment by YoshifumiFuyuno** [comment]
Done. Version 6.2.1
