### ISSUE TITLE
Allow popup on editable fields with hold alt when Opening behavior is set to auto

### ISSUE THREAD

**Issue by RLSmithy** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#5]
Currently, when opening behavior is set to auto. In most of the cases it is not useful and annoying when selecting and editing text. In some cases, I would likte to have the pop-up showing up, therefore it would be cool if there is an additional feature to make it possible to show up the pop-up with e.g. holding alt and selecting the text in an editable field, but in other cases to have the pop-up behavior set to auto.

**Comment by YoshifumiFuyuno** [comment]
Hi.

Similar things are already possible.
<a href="#SPC!Options"><img src="https://raw.githubusercontent.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/57db9db/src/res/icons/icon48.png" width="16">add-on options</a> -> "Popup/icons behaviour" -> "Allow popup on editable fields"
By unchecking the check box, it will not be automatically displayed in the editable field.
If you want to show popup, you can use the "Toggle open/close popup" shortcuts (default: Ctrl+Shift+Space).

The shortcuts can be modified by the user within the limits of the browser.
https://github.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/wiki/Instructions#change-keyboard-shortcuts

Best regards
