### ISSUE TITLE
Support for XHR search

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#50]
### Is your feature request related to a problem? Please describe.

Some search engines do not support either GET or POST.

Here's an example: `https://search.obvsg.at/primo-explore/search?vid=OBV`

Go to this website. When you search, it creates a GET request, but you can't use it as a search URL. This GET request is only an XHR request for loading data. There is no version of this search that does not use XHR.

### Describe the solution you'd like

1. the website is opened in a new tab
2. the search query is typed into the search box automatically
3. search is run by pressing enter or by clicking on an element that was indicated by the user

### Describe alternatives you've considered

Using JavaScript code is a workaround, but it would be nice to add a generic XHR search engine functionality that can also be automatically added using the right click menu, like other search engines can be added.

**Comment by cheater** [comment]
Another example:
`https://www.avnet.com/wps/portal/ebv/`

Another example is online email.

**Comment by Pikcee** [comment]
Does that also applies to `https://readm.org/` by any chance?

**Comment by cheater** [comment]
Yes, although in your case, there is no search confirmation, as search results are shown as you're typing.

**Comment by YoshifumiFuyuno** [comment]
- search.obvsg.at
`https://search.obvsg.at/primo-explore/search?query=any,contains,{searchTerms}&vid=OBV`
- Gmail
`https://mail.google.com/mail/u/0/#search/{searchTerms}`

Since the DOM structure and monitored events are different for each site, it is impossible to generalize it.
For example, avnet.com, which you mentioned as an example, is changing the page with JavaScript, and even if you enter a value in the value of the input box immediately after the page is loaded, it will be deleted.
Such sites need to be scripted individually.

**Comment by cheater** [comment]
Thanks for the obvsg search url. How did you obtain it? I wasn't able to
figure it out, all I saw was an XHR request, which returned broken HTML if
I visited it.

Regarding avnet. A good heuristic around that would be to enter the search
terms 0.5 sec after the website is loaded. Then what you really need is 1)
where to enter the search terms and 2) what to click after (if anything).
It seems like this would be enough of a heuristic to cover anything - but
we won't know if we can't try it out in testing. So I imagine we'd have a
search engine that's called "scripted", just like "GET" or "POST", and it
would have the following entry boxes in the menu editor:

1. website url
2. delay before entering search terms, in seconds, allowing fractional
seconds as well
3. css selector of text box where to enter the data
4. another delay before pressing some sort of button to return search
results
5. css selector of button to click on (or don't do anything if it's empty)

What do you think?

**Comment by YoshifumiFuyuno** [comment]
I got it from the omnibox.
As I mentioned above, wait time is unreliable, but I will consider it.
