### ISSUE TITLE
Pretty-print settings backup

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#51]
### Is your feature request related to a problem? Please describe.

I'd like it to be easier to share my settings and search engines with other people, but the JSON output is on one single line. Please pretty-print it so it's easier to work with.

### Describe the solution you'd like

-

### Describe alternatives you've considered

Currently an external pretty printing tool or website has to be used which is an annoying extra step.

**Comment by YoshifumiFuyuno** [comment]
Most editors such as VSCode, Emacs, Notepad++, etc. have settings or plugins to auto-format JSON, so I'm not thinking of implementing them at the moment.
A better way would be to use a json editor.

**Comment by cheater** [comment]
There is no need to implement anything. When you call JSON.stringify(), one
of the parameters allows you to pretty-print.

Not everyone knows their way around a code editor.

I've tried to look up where this is in the SPC code, but I haven't found
the code - have you made this project closed source? I was under the
impression it was open source, just as SSS was.

**Comment by cheater** [comment]
Here's the doc for this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#the_space_argument

if I can fork this project, then I'll be able to provide this change to you (as well as a bunch of other stuff I requested), so you won't have to do it yourself.

**Comment by YoshifumiFuyuno** [comment]
I know, but the reason I don't implement it is because the backup file should be as small as possible.
The reason why the source is not released now is #52.

**Comment by cheater** [comment]
ok, but it's not going to be much bigger though? it's still a few kb in
size. the only thing that can make it large is data urls.
