### ISSUE TITLE
老是报错

### ISSUE THREAD

**Issue by Monster-DP** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#63]
### Describe the bug

我也不知道是怎么报错的，我记得清楚错误后可以正常使用，用着用着就又会报错
![image](https://user-images.githubusercontent.com/47738288/206967316-de4b5b82-1812-4b06-b20f-08082829312e.png)
![image](https://user-images.githubusercontent.com/47738288/206967460-4e5c7e8f-f2bb-409c-9d60-ae940fc1dd6b.png)

### To Reproduce

1. Start Browser with clean profile.
2. Install SPC.
3. 
4. 

### Expected behavior

无

### Actual behavior

无

### Your Environment

```markdown
- OS: [Windows 11]
- Browser [猫眼浏览器 Catsxp: 版本 2.12.4]
- Extension Version [7.1]
```

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thank you for reporting.

this browser?
https://www.catsxp.com/

I used the installer but it was very slow and indicated it would take 4 hours to download so it is impossible to try.
What kind of operation causes the error?
Incidentally, no such error occurs in Google Chrome 108.0.5359.99.

I will try the installation again this Sunday.

Best regards

**Comment by YoshifumiFuyuno** [comment]
你好。

我已经安装了 Catsxp 2.12.5。

我认为“Unchecked runtime.lastError: Cannot find menu item with id 2”是问题所在，
我只是无法重现它。

如果发生错误，SPC是否停止工作？
如果它工作正常，您可能不必担心。

如果您不需要上下文菜单搜索，禁用 <a href="#SPC!Options"><img src="https://raw.githubusercontent.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/57db9db/src/res/icons/icon48.png" width="16">add-on options</a> -> "Context menu" -> "Is the context menu enabled?" 可能会有所帮助。

**Comment by Monster-DP** [comment]
![image](https://user-images.githubusercontent.com/47738288/208293722-781e098a-d59d-4c32-82bc-82295c0a9a66.png)
问题依然存在，发生错误后SPC无法工作

**Comment by YoshifumiFuyuno** [comment]
感谢您的截图。 容易明白。
如果可能的话，你能把配置文件发给我吗？ (<a href="#SPC!Options"><img src="https://raw.githubusercontent.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/57db9db/src/res/icons/icon48.png" width="16">add-on options</a> -> "Storage & backup" -> "Export options to file")
另外，你是否安装了其他附加组件？

**Comment by Monster-DP** [comment]
[SPC settings backup (20221220-080305).zip](https://github.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/files/10263610/SPC.settings.backup.20221220-080305.zip)
![catsxp_screenshot_extensions](https://user-images.githubusercontent.com/47738288/208551630-bd6b9f41-d64b-402b-b2c4-18dbbf90c58c.png)
![catsxp_screenshot_extensions (1)](https://user-images.githubusercontent.com/47738288/208551635-1ae4b2d1-211c-4ece-ae85-ae03dce745ba.png)
![catsxp_screenshot_extensions (2)](https://user-images.githubusercontent.com/47738288/208551644-fb864a17-2a70-4ec4-a357-abed7ee94c75.png)

**Comment by Monster-DP** [comment]
感谢 爱你呦！

**Comment by YoshifumiFuyuno** [comment]
结束了。
7.2版已经提交。
Mozilla和Microsoft审查可能需要长达7个工作日。

要更新，请下载并解压更新后的crx并覆盖扩展目录。

最好的问候。
