### ISSUE TITLE
Open Folder on click

### ISSUE THREAD

**Issue by Pikcee** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#64]
### Is your feature request related to a problem? Please describe.

The current behavior of SPC is to open any folder on hover which is quite disturbing most of the times and inconvenient (sometimes even multiple folders stuck open, overlapping the other engines and each others)

### Describe the solution you'd like

Please make it possible to open folders only when really needed (on click)

### Describe alternatives you've considered

​

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thank you for your suggestion.

The click may be used for other actions, so I'm thinking of allowing you to set the wait time after hovering instead.

I will consider clicking if there are many requests.

Best regards

**Comment by Pikcee** [comment]
> 

there shouldn't be any kind of conflict or issue for just making a folder open only when you click on it,
I've tons of search engines and folders and I rely on your extension a lot, would you please reconsider

**Comment by YoshifumiFuyuno** [comment]
It doesn't currently conflict, but I envisioned a future feature like clicking on a folder would search all engines in the folder.
However, I know what you want and will make it possible to open a folder with a click in the next version.

**Comment by Pikcee** [comment]
> It doesn't currently conflict, but I envisioned a future feature like clicking on a folder would search all engines in the folder. However, I know what you want and will make it possible to open a folder with a click in the next version.

Thank you very much , this will be really helpful!

Regarding the "search all engines in a folder" feature If I may express my opinion, a click on a folder could happen by mistake (such accident most probably wouldn't be fun especially in case the folder holds a lot of engines XD ).
if you decided to implement the multiple search folder feature in the future something like a double right click could be used (or even triple), 
ctrl+click or ctrl+right click, there are a lot of options but I believe it shouldn't be something direct like a click,
since generally for any type of software, behaving like the user expect provides the best user experience, regardless I will respect your decision whatever you ended up deciding

I really love your extension and rely on it all the time
I would like to express my thanks once more... sincerely <3

**Comment by YoshifumiFuyuno** [comment]
Done.
I submitted version 7.2.
Mozilla and Microsoft reviews may take up to 7 business days.

Thank you again for your valuable feedback.

Best regards

**Comment by Teko101** [comment]
> It doesn't currently conflict, but I envisioned a future feature like clicking on a folder would search all engines in the folder.

That's a great idea. May I suggest adding an option to open them in unloaded tabs? I think such option should be included in general, because there's already an option to search multiple engines at once, and a click by mistake won't be a big problem if the tabs are unloaded because they won't affect the browser performance, and you can close them all in 2 clicks.

I guess the option can be something like: 
Minimum Number of tabs to open as unloaded: USER_INPUT

I just wanna second what @Pikcee said about your work, it's really helpful... thanks
