### ISSUE TITLE
Lazy loading when opening multiple tabs

### ISSUE THREAD

**Issue by YoshifumiFuyuno** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#66]
> It doesn't currently conflict, but I envisioned a future feature like clicking on a folder would search all engines in the folder.

That's a great idea. May I suggest adding an option to open them in unloaded tabs? I think such option should be included in general, because there's already an option to search multiple engines at once, and a click by mistake won't be a big problem if the tabs are unloaded because they won't affect the browser performance, and you can close them all in 2 clicks.

I guess the option can be something like: 
Minimum Number of tabs to open as unloaded: USER_INPUT

I just wanna second what @Pikcee said about your work, it's really helpful... thanks

_Originally posted by @Teko101 in https://github.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/issues/64#issuecomment-1407864578_

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thanks for the idea.
I think lazy loading when opening multiple tabs is a very good idea.
I made a test version and it seems to work fine.
If there is no problem, I think that I can publish it on Saturday or Sunday.

Best regards

**Comment by Teko101** [comment]
That's awesome. Thank you so much :)

**Comment by YoshifumiFuyuno** [comment]
Hi.

Done.
I submitted version 7.3.
Mozilla and Microsoft reviews may take up to 7 business days.

Best regards
