### ISSUE TITLE
Clipboard problem in combination with kde-connect

### ISSUE THREAD

**Issue by ghost** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#68]
### Describe the bug

Hey there, great fork of a great addon. 
I'm having a little problem when using this addon in combination with kde-connect.
I set the opening behavior of the addon to Auto (double click on anything and the pop-up shows up).
When I copy something to the clipboard via the pop-up and kde-connect is running on the same computer, kde-connect picks up the copied text, but SPC does not.
When kde-connect is not running, it works perfectly fine and picks up the copied text.
 Don't know if this can be fixed in SCP or kde-connect is causing the problem.

### To Reproduce

1. Start Browser with clean profile.
2. Install SPC.
3. Install kde-connect on Windows PC
4. Copy something to the clipboard
5. Paste from the clipboard shows nothing

### Expected behavior

I would expect the text to be copied to the clipboard and be usable by normal paste and also by kde-connect.

### Actual behavior

Copied text can not be pasted via CTRL+V or via paste, but can be used via kde-connect.

### Your Environment

```markdown
- OS: Windows 10 (22H2 19045.2846)
- Browser: Librewolf 112.0.2-1
- Extension Version: 7.4
```

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thank you for reporting.

I tried building the same environment, but I could not reproduce it here.
Am I misunderstanding something?
[Video.webm](https://user-images.githubusercontent.com/9511854/236673797-d675d513-5643-4544-a192-0c339d88ee5d.webm)

Best regards

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thank you for reporting.

I tried building the same environment, but I could not reproduce it here.
Am I misunderstanding something?

Best regards

https://user-images.githubusercontent.com/9511854/236673797-d675d513-5643-4544-a192-0c339d88ee5d.webm
