### ISSUE TITLE
Popup does not work in Bing chat (in edge at least)

### ISSUE THREAD

**Issue by Hosseingsd** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#69]
### Describe the bug

Greetings! I would like to express my gratitude for providing such a useful addon that has helped me save a considerable amount of time and energy. However, I have noticed that your popup fails to appear when I select any text in the chat while chatting with Bing chat. I kindly request you to fix this issue.

### To Reproduce

1. Start chat with Bing chat (AI)
2. send a message
3. select any text
4. wait forever for the popup :))

### Expected behavior

displaying popup after selecting text

### Actual behavior

popup does not appear in Bing chat

### Your Environment

```markdown
- OS: Windows 10
- Browser Version 114.0.1823.43 (Official build) (64-bit)
- Extension Version 7.4
```

### Additional context

I talked to Bing chat about this issue an heres Bing Chat's Ideas:

> 
> I see. That is indeed a problem. I apologize for the inconvenience that this causes you. 😔
> 
> I have looked into the possible causes of this issue and I have found that it might be related to the way the chat with Bing is implemented. The chat with Bing uses a web component called **shadow DOM** that isolates the chat content from the rest of the webpage. This means that the popup tool might not be able to access the text or image that you select in the chat with Bing, because it is hidden inside the shadow DOM.
> 
> One possible solution to this problem is to enable the **Expose shadow DOM** option in the popup tool settings. This option allows the popup tool to search inside the shadow DOM elements on a webpage. However, this option might not work on all websites and it might affect the performance of the popup tool.
> 
> Another possible solution is to copy and paste the text or image that you want to search from the chat with Bing to another webpage or application, and then use the popup tool there. This is not very convenient, but it might be a workaround until I can find a better way to fix this issue.
> 
> I hope this helps you. Please let me know if you have any questions or feedback. I appreciate your patience and understanding. 🙏
> 
> : [Shadow DOM v1: Self-Contained Web Components | Web Fundamentals | Google Developers]
> : [Search from Popup or Context Menu - Microsoft Edge Addons]

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thank you for reporting.

I couldn't reproduce this at first, but now I know.
Do you set "Opening behavior" to "auto"?

Sorry, I'm very busy this month and won't be able to research or fix the cause of the problem until next month.

As a temporary workaround until a fix:
- Change "Opening behavior"
- Use shortcut keys
   edge://extensions/shortcuts
- Click the SPC icon in the toolbar

Best regards

**Comment by Hosseingsd** [comment]
Hello,

Do I set "Opening behavior" to "auto"? Yes.

I will use the hotkeys as a workaround until the issue is resolved.

Thank you.

**Comment by YoshifumiFuyuno** [comment]
I'm sorry to have kept you waiting.
I submitted version 8.0.
Mozilla and Microsoft reviews may take up to 7 business days.

Thank you again for your valuable feedback.

Best regards
