### ISSUE TITLE
Customise suggestion url

### ISSUE THREAD

**Issue by khabib227** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#70]
### Is your feature request related to a problem? Please describe.

Implement text field to customise suggestion url

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thank you for your suggestion.

This can be done by exporting the configuration, changing the "popupSuggestURI" and then importing it.
A Search query will be added to the end of the URL.
"Storage & backup" -> "Export options to file" / "Import options from file"

Many people don't know the SuggestURI, so I think having a text field just gets in the way.
Instead, add the change instructions to the Wiki.

Best regards

**Comment by khabib227** [comment]
Yes adding it to wiki would be very good, thanks!
