### ISSUE TITLE
Hotkey as preffix and/or suffix

### ISSUE THREAD

**Issue by khabib227** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#73]
### Is your feature request related to a problem? Please describe.

Allow use a hotkey as preffix and/or suffix for instance if I have Bing Images with "bi" hotkey allow this in the popup text field: 

Whitney Houston bi 

or

bi Whitney Houston

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

**Comment by YoshifumiFuyuno** [comment]
Hi.

If you include "bi" in the engine name:
1. press tab key in text field (caret moves to "Engine filter")
1. input bi
1. press enter

you can do the same with.

Best regards
