### ISSUE TITLE
Button to convert favicon to base64

### ISSUE THREAD

**Issue by khabib227** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#74]
### Is your feature request related to a problem? Please describe.

Today I copy the image link from favicon using context menu over the favicon that is in the left side of the engine title and after I paste it to icon field, would be very good a button to automatize this.

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thank you for your suggestion.

If you add a search engine from the context menu or options page, cache the favicon as data: scheme (base64).
So you don't have to convert it yourself.

Best regards

**Comment by khabib227** [comment]
Even if the site change the icon, the extension keep the cached one or the icon is updated? I'm asking it because I ever use base64, because sometimes one site change the icon to one very bad icon, like Bing, in the past Bing used B as icon, now has a loupe as icon, so I use base64 to avoid bad changes in icons, keeping it easy to be identified.

**Comment by YoshifumiFuyuno** [comment]
The icon will only change if:
* When a configuration file is imported from local or Sync.
* When you change the icon URL on the options page
* When you reset the settings.
