### ISSUE TITLE
Context Menu respect mouse buttons

### ISSUE THREAD

**Issue by khabib227** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#76]
I don't know if it is possible with Firefox, but would be good if context menu respect the mouse buttons, for instance if I click in an search engine with left click open in current tab, if I use middle click open in a new tab.

And congrats again, very good your fork!

**Comment by YoshifumiFuyuno** [comment]
The behavior of the mouse in the context menu can be changed from the settings.
<a href="#SPC!Options"><img src="https://raw.githubusercontent.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/57db9db/src/res/icons/icon48.png" width="16">add-on options</a> -> "Context menu"
* "Context menu item click behaviour"
* "Context menu item Middle mouse button click (Firefox Only)"
* "Context menu item Right mouse button click (Firefox Only)"

Thank you for the compliment. I'm happy:smile:

**Comment by khabib227** [comment]
Thanks! The setting was what I wanted. :D
