### ISSUE TITLE
Popup doesn't work anymore on editable fields

### ISSUE THREAD

**Issue by Teko101** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#78]
### Describe the bug

After the last update, the popup box doesn't show when text is selected in editable text field. I'm not sure If it's just me or not.
('Allow popup on editable fields' option is checked)

### To Reproduce

1. Start Browser with clean profile.
2. Install SPC.
3. 
4. 

### Expected behavior

No Response

### Actual behavior

No Response

### Your Environment

```markdown
- Windows 7, Windows11
- Firefox 115.0.1 
- Extension Version SPC 8.0.1
```

**Comment by keldian** [comment]
Same here. KDE neon 5.27 / Fx 115.0.2 / SPC 8.0.1

**Comment by YoshifumiFuyuno** [comment]
Hi.

Sorry for my late reply.
Thank you for reporting.
I submitted version 8.0.2.
Mozilla and Microsoft reviews may take up to 7 business days.

Best regards
