### ISSUE TITLE
Disable under specified circumstances/environments

### ISSUE THREAD

**Issue by PMTabs** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#81]
### Is your feature request related to a problem? Please describe.

There are certain sites on which I don't want the add-on to be active. It can cause issues with live-edit websites such as Google Sheets, for example.

I'd also like to be able to automatically disable the add-on when I have the Ctrl+F dialogue open, as the popup often obscures what I'm searching for on the page (the popup is triggered because the page search highlights the word for you).

### Describe the solution you'd like

A user-edited list of 'Ignore' URLs, which automatically disables the add-on's functionality when the user browses those URLs, would be very helpful.

An option in the add-on's settings which prevents the popup from appearing when the Ctrl+F search box is open.

### Describe alternatives you've considered

Manually disabling the add-on when I'm working on Google Sheets, or if I need to do a lot of searching within a page's text.

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thank you for your suggestion.

There is already a feature that prevents popup from working on specific URLs.
"General" -> "Bookmarklet: Auto-execute Bookmarklet"
https://github.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/wiki/Auto-execute-Bookmarklet

```javascript
if(location.href.startsWith("https://docs.google.com/spreadsheets/")) {
  return true;
}
```

As for Ctrl+F, I don't think there is any way to detect the browser search function.
However, I would like to support it in the future.

Best regards

**Comment by YoshifumiFuyuno** [comment]
Hi.

Disable popup with Ctrl+F.
Done.
I submitted version 8.1.
Mozilla and Microsoft reviews may take up to 7 business days.

Best regards

**Comment by PMTabs** [comment]
Wow, solutions to both scenarios! Thank you so much.
