### ISSUE TITLE
Popup appears without icons on 1337x.to

### ISSUE THREAD

**Issue by aon33** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#86]
### Describe the bug

Highlight any text on https://1337x.to and popup will appear but without any icons.

![1911 13_firefox](https://github.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/assets/158162068/5cbd2b23-f3f3-40a3-b7fa-b4cc35dee0c6)

### To Reproduce

1. Start Browser with clean profile.
2. Install SPC.
3. https://1337x.to
4. Highlight any text and popup without icons

### Expected behavior

Popup with icons

### Actual behavior

Popup without icons

![1911 13_firefox](https://github.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/assets/158162068/c28d3c5b-e2e0-4f30-bfe6-9da2e5980598)

### Your Environment

```markdown
- OS: Windows 7
- Browser Firefox
- Extension Version 8.1
```

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thank you for reporting.

I couldn't reproduce it.🤔
![1](https://github.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/assets/9511854/90206d3f-02fd-43e7-88cb-c9b726b4d872)
- OS: Windows 10
- Browser Firefox 122.0
- Extension Version 8.1

What version of Firefox are you using?

Best regards

**Comment by aon33** [comment]
Firefox 115.7.0esr (64-bit)

Very strange, seems like only this site got this problem.  Thank you.

For mine, only the Options icon and Separators visible on this site.  But if I move my mouse pointer slowly, I can still click on the invisible icons blindly.  It is like all the icons got squeezed together until they are invisible.

**Comment by aon33** [comment]
Sorry, I decided to try something new.  I disabled uBlock Origin and the icons now appear normally.  I will investigate further, thank you.

**Comment by aon33** [comment]
Okay, I managed to isolate the cause to the "Easylist Ads" filter list.  Unchecking it allow SPC to show all its icons now.

![2235 13_firefox](https://github.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/assets/158162068/2284313f-6709-428b-a8b0-e75bdc886b1a)

**Comment by YoshifumiFuyuno** [comment]
To keep "Easylist Ads" enabled, it seems that you can add either of the following to uBlock Origin My filters.

```
! 1337x only
1337x.to#@#img[src*="data:image"]
```
or
```
! all site
#@#img[src*="data:image"]
```
