### ISSUE TITLE
Extension hijacks default search on address bar

### ISSUE THREAD

**Issue by savvasdalkitsis** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#91]
### Describe the bug

Great addon but I cannot find a way to disable it hijacking my default search on address bar. I'm on Edge and have set a default search engine for my address bar. Despite that, whenever i perform a new search, the extension opens up the following page:

extension://hlikagndoiibjkblhopoajeonpkfgiko/?q=test

![image](https://github.com/user-attachments/assets/ae864088-97f8-4aa5-91c7-5c8b0fe0e03d)

### To Reproduce

Install the extension
Set a default search engine for the address bar
Perform a new search

### Expected behavior

A search is executed using your default search engine

### Actual behavior

The extension hijacks the request and opens up the following page:

extension://hlikagndoiibjkblhopoajeonpkfgiko/?q=test

![image](https://github.com/user-attachments/assets/ae864088-97f8-4aa5-91c7-5c8b0fe0e03d)

### Your Environment

```markdown
- OS: Windows 11
- Browser Edge 127.0.2651.74
- Extension Version 8.1
```

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thank you for reporting.
I can't reproduce it, am I doing something wrong?
Best regards

https://github.com/user-attachments/assets/bb4fb21c-3523-467a-848f-3d4b6750ea64

**Comment by savvasdalkitsis** [comment]
hm i think it is because the extension defaults to using 's' as its default key and i had already assigned that to my custom search engine before installing the plugin

**Comment by savvasdalkitsis** [comment]
That was definitely it. I changed my search engine's key and it works fine now
